CREATE TABLE [dbo].[Game]
(
	[GameID] INT NOT NULL IDENTITY(1,1),
	[Name] NVARCHAR(999) NOT NULL,
	[Email] NVARCHAR(999) NOT NULL,
	[DateTime] DATETIME NOT NULL,
	[Venue] NVARCHAR(999) NOT NULL,
	[Total] MONEY NULL,
	CONSTRAINT PK_GameID PRIMARY KEY ([GameID]),
	CONSTRAINT FK_Email FOREIGN KEY (Email) REFERENCES People (Email)

)
